[package]
name = "max31865"
version = "0.1.0"
authors = ["Rudi Horn <dyn-git@rudi-horn.de>"]
keywords = ["embedded-hal-crate", "rtd-sensor"]
categories = ["embedded", "no-std", "hardware-support"]
description = "A generic driver for the MAX31865 RTD to Digital converter"
repository = "https://github.com/rudihorn/max31865"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = { version = "0.1.2", features = ["unproven"] }
